version: "3.9"

services:

  java-app:
    container_name: travsky-app
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://java_db:3306/bbdd-hackacode?createDatabaseIfNotExist=true&serverTimezone=UTC
      MYSQL_USER: root
      MYSQL_PASS: 1234
    restart: always
    depends_on:
      java_db:
        condition: service_healthy

  react-app:
       container_name: react_app
       build: ../frontend/dist
       ports:
           - "5173:5173"
       restart: always
       depends_on:
         java-app:
           condition: service_healthy

  java_db:
    container_name: java_db
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bbdd-hackacode
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10